<a href="https://colab.research.google.com/github/mjvnc37/DataScince-in-python/blob/main/3)numeric_analysis_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
#create a id array
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8])
print(arr1)


[1 2 3 4 5 6 7 8]


In [ ]:
#access and manipulate elements in the array
arr1[2]

3

In [ ]:
#change element
arr1[2]=5
arr1

array([1, 2, 5, 4, 5, 6, 7, 8])

In [ ]:
#create 2-D array & check the shape of the array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#check shape of the array
print("The shape is 2 rows and 3 columns:",arr2.shape)

The shape is 2 rows and 3 columns: (2, 3)


In [ ]:
#access element from 2 d array
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])


3
3
3
4


In [ ]:
#create an array of string
arr3=np.array(['India','china','USA','japan'])
print(arr3)

['India' 'china' 'USA' 'japan']


In [ ]:
#arrange()&linespace()values in shape
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
#create array of random values bw 0&1 in a given shape
arr=np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

[0.94575172 0.88309652 0.63094776 0.7172427  0.36208007 0.15088257
 0.66673449 0.70158404 0.59153842 0.37038474]


[[0.32036532 0.21701663 0.26846404 0.34860093]
 [0.6943763  0.01825445 0.45358947 0.59129779]
 [0.53062852 0.96509667 0.16210016 0.90116563]]


In [ ]:
#create constant value
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [ ]:
#repeat element using  repeat()& tail()
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [ ]:
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [ ]:
#create identity matrix using eye() &identity()
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#identity()
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#create 5*5 2D array for random numbers bw0&1
arr=np.random.rand(5,5)
print(arr)

[[0.22717339 0.24588067 0.31083513 0.27797305 0.03168547]
 [0.52412742 0.84491705 0.27723015 0.18140193 0.46784739]
 [0.36977643 0.24339707 0.54981201 0.10643583 0.41339496]
 [0.20430058 0.93708932 0.75171444 0.55652209 0.31070776]
 [0.71031364 0.91038817 0.44101188 0.65719335 0.72985601]]


In [ ]:
#sum along the column
print(np.sum(arr,axis=0))

[2.03569146 3.18167229 2.33060362 1.77952625 1.95349159]


In [ ]:
#calculate mean.medin,sd&variance
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))


0.45123940773095134
0.4133949633214852
0.25122949808078754
0.06311626070592442


In [ ]:
#sort an array sort()
print(np.sort(arr,axis=1))

[[0.03168547 0.22717339 0.24588067 0.27797305 0.31083513]
 [0.18140193 0.27723015 0.46784739 0.52412742 0.84491705]
 [0.10643583 0.24339707 0.36977643 0.41339496 0.54981201]
 [0.20430058 0.31070776 0.55652209 0.75171444 0.93708932]
 [0.44101188 0.65719335 0.71031364 0.72985601 0.91038817]]


In [ ]:
print(np.sort(arr,axis=0))

[[0.20430058 0.24339707 0.27723015 0.10643583 0.03168547]
 [0.22717339 0.24588067 0.31083513 0.18140193 0.31070776]
 [0.36977643 0.84491705 0.44101188 0.27797305 0.41339496]
 [0.52412742 0.91038817 0.54981201 0.55652209 0.46784739]
 [0.71031364 0.93708932 0.75171444 0.65719335 0.72985601]]


In [ ]:
#append
arr=np.array([4,4,6,7])
arr1=np.append(arr,8)
arr1

array([4, 4, 6, 7, 8])

In [ ]:
arr2=np.append(arr2,[9,10,11])
print(arr2)

[ 1  2  3  4  5  6  9 10 11]


In [ ]:
#concatienate
arr1=np.array([[1,2,3],[3,8,6]])
arr2=np.array([[5,6,7],[3,7,5]])
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3]
 [3 8 6]
 [5 6 7]
 [3 7 5]]


In [ ]:
#concatienate
arr1=np.array([[1,2,3],[3,8,6]])
arr2=np.array([[5,6,7],[3,7,5]])
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 5 6 7]
 [3 8 6 3 7 5]]


In [ ]:
arr2=np.array([4,5,6,7,8])
print(arr2)
print('\n')
arr=np.delete(arr2,[1,4])

[4 5 6 7 8]


